# Funding options for SEO Analyst Agent

github: # Add your GitHub username if you want sponsorship
# patreon: # Add your Patreon username
# ko_fi: # Add your Ko-fi username
# custom: # Add custom sponsorship URLs
